
### регистрация

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "superpassword",
  "name": "Alex"
}
### логин
POST http://localhost:3000/api/auth/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzgxMjU4NzM0LCJleHAiOjE3ODEzNDUxMzR9.7gFV_aEuof8VZliixp496y7Ue0hIKSuiA8MrnpR9HoY

{
  "email": "test@test.com",
  "password": "superpassword"
}

### чаты - получить все
## получить список чатов

GET http://localhost:3000/api/chats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzgxMjU4NzM0LCJleHAiOjE3ODEzNDUxMzR9.7gFV_aEuof8VZliixp496y7Ue0hIKSuiA8MrnpR9HoY
### чаты - создать

POST http://localhost:3000/api/chats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNzgxMjU4NzM0LCJleHAiOjE3ODEzNDUxMzR9.7gFV_aEuof8VZliixp496y7Ue0hIKSuiA8MrnpR9HoY

{
  "guestId": 1,
  "title": "Новый чат 1"
}

###